# Generated by Django 4.2.6 on 2023-11-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogsHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='likes',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='likes',
            name='like_status',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (0, 'Neutral'), (-1, 'Dislike')], default=0),
        ),
    ]
