# Generated by Django 4.2.7 on 2025-03-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogsHub', '0002_alter_comments_options_remove_likes_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_main_images'),
        ),
    ]
