# Generated by Django 4.2.6 on 2023-11-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToursHub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='People_count',
            new_name='people_count',
        ),
    ]
