# Generated by Django 4.2.6 on 2023-10-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToursHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinations',
            options={'ordering': ['country', 'provinces', 'location']},
        ),
        migrations.AlterModelOptions(
            name='tourprograms',
            options={'ordering': ['day']},
        ),
        migrations.AlterModelOptions(
            name='tours',
            options={'ordering': ['created_at']},
        ),
    ]
