# Generated by Django 4.2.6 on 2023-10-26 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToursHub', '0002_alter_destinations_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourfacilitiesincluded',
            name='tour_facility_included',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_facilities_included', to='ToursHub.tours'),
        ),
    ]
