# Generated by Django 4.2.6 on 2023-11-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursHub', '0002_rename_people_count_tours_people_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='tour_main_image',
            field=models.ImageField(blank=True, upload_to='tours'),
        ),
    ]
