# Generated by Django 4.2.6 on 2023-11-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursHub', '0003_alter_tours_tour_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='tour_main_image',
            field=models.ImageField(blank=True, null=True, upload_to='tours'),
        ),
    ]
