# Generated by Django 4.2.6 on 2023-10-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursHub', '0005_tourbooking_bookingusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
