# Generated by Django 4.2.7 on 2023-11-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursHub', '0005_alter_tours_tour_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='price_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='total_adults',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='total_children',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='total_infants',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
