# Generated by Django 4.2.6 on 2023-10-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToursHub', '0006_alter_tours_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='tour_destination',
            new_name='tour',
        ),
        migrations.RenameField(
            model_name='tourfacilitiesincluded',
            old_name='tour_facility_included',
            new_name='tour',
        ),
    ]
