# Generated by Django 4.2.7 on 2025-01-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursHub', '0006_tourbooking_price_currency_tourbooking_total_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='duration',
            field=models.SmallIntegerField(),
        ),
    ]
