# Generated by Django 4.2.7 on 2025-03-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursHub', '0007_alter_tours_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourfacilities',
            name='icon',
        ),
        migrations.AddField(
            model_name='tourprograms',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs'),
        ),
    ]
