# Generated by Django 4.2.6 on 2023-10-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToursHub', '0007_rename_tour_destination_destinations_tour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='tour_name',
            new_name='tour_title',
        ),
    ]
