# Generated by Django 4.2.6 on 2023-11-05 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToursHub', '0008_rename_tour_name_tours_tour_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourfacilities',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourfacilities',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tour_facilities', to='ToursHub.tours'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TourFacilitiesIncluded',
        ),
    ]
