# Generated by Django 4.2.7 on 2025-03-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursHub', '0008_remove_tourfacilities_icon_tourprograms_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourreviews',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
