# Generated by Django 4.2.7 on 2025-03-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursHub', '0009_alter_tourreviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourreviews',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
